System stack but not really
nicolas-risberg/NewEngine pull request #27
Opened 2024-08-26 19:07 UTC by Aki-Gonzalez

Allows for queueing add & remove systems.
Made multiple templetized methods for interacting with World's Systems.

2024-08-26 21:37 UTC, wejdell requested changes

2024-08-26 21:37 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.cpp
> +		for (U16 i = 0; i < SystemsToAdd.size(); i++)
Probably no reason to use an indexed loop here, can you make it a for each?

2024-08-26 21:37 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.cpp
> +			Systems[i] = std::move(Systems[next]);
Looks like you're wanting a call to std::swap here? think it might invalidate previous systems otherwise, at the very least at `index`.

2024-08-26 21:37 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.h
> +		HAVTORN_API inline TSystem* GetSystem();
I'm pretty sure you shouldn't export template functions, double check this

2024-08-26 21:37 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.h
> +			const U64 HashCode;
Think it's a good idea to define a default value here, 0 should be fine

2024-08-26 21:37 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.h
> +		struct SystemTypeCode
Is this used?

2024-08-29 17:33 UTC, Aki-Gonzalez commented on Havtorn/Source/Engine/Scene/World.h
> +		struct SystemTypeCode
Yes

2024-08-29 17:34 UTC, Aki-Gonzalez commented on Havtorn/Source/Engine/Scene/World.h
> +		HAVTORN_API inline TSystem* GetSystem();
I'll check. We do use it in the other projects though. So there is a need (?). Will have to figure out something else if we can't export.

2024-08-29 17:36 UTC, Aki-Gonzalez commented on Havtorn/Source/Engine/Scene/World.cpp
> +			Systems[i] = std::move(Systems[next]);
Swap is nice, I forgot it exists. The idea is to invalidate the previous system, the one we want to remove.

2024-08-29 17:38 UTC, wejdell commented on Havtorn/Source/Engine/Scene/World.cpp
> +			Systems[i] = std::move(Systems[next]);
What I mean is I think it might invalidate all the ones on the way to the back, if I'm understanding it correctly

2024-08-29 18:00 UTC, wejdell approved these changes

2024-08-29 18:00 UTC, merged